# Generated by Django 3.1.5 on 2021-01-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
