# Generated by Django 3.1.5 on 2021-01-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_auto_20210131_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='fullname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
