# Generated by Django 3.1.5 on 2021-01-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_auto_20210131_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='desc',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='detail',
            name='shdesc',
            field=models.TextField(default='', max_length=30),
        ),
    ]
